name: Test
on: [push]

jobs:
  build:

    runs-on: tests

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven
      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.1
      - name: Sleep for 60 seconds
        run: Start-Sleep -s 60
        shell: powershell
      - name: Run Test
        run: mvn test -Dtest=SeleniumTest#test
      - name: Run ImpactAnalyzer
        run: mvn test -Dtest=ImpactAnalyzerTest#Test
