name: Tests
on: [push]

jobs:
  build:

    runs-on: tests

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven
      - name: Clean Install
        run: mvn clean install -DskipTests
      - name: Run Test
        run: mvn -Dtest=UserMultiplePages test
      - name: Run Test
        run: mvn -Dtest=FindOwner test
      - name: Run ImpactAnalyzer
        run: mvn test -Dtest=ImpactAnalyzerTest#Test
